spring.application.name=backend-java

server.port=8081

#datasource h2
#spring.datasource.url=jdbc:h2:mem:banco
#spring.datasource.username=sa
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

#datasource postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/flow_trader
spring.datasource.username=
spring.datasource.password=
spring.datasource.platform=postgres
spring.database.driverClassName=org.postgresql.Driver

#JPA h2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

#JPA postgres
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#h2
#spring.h2.console.enabled=true
#spring.h2.console.path=/banco
